site_name: Hak Lee
theme:
  name: material
  font:
    text: Noto Sans Korean
    code: Noto Sans Korean
  palette:
    primary: black
  logo: assets/transparent-40x40.png
  favicon: assets/transparent-40x40.png
  features:
    - navigation.tabs

nav:
  - home: index.md
  - about: about.md

plugins:
  - search
  - awesome-pages
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: ko
          default: true
          name: 한국어
          build: true
        - locale: en
          name: English
          build: true

markdown_extensions:
  - attr_list

extra:
  generator: false

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2024 - <script>document.write(new Date().getFullYear());</script> Hak Lee